name: docs
channels:
  - conda-forge
dependencies:
  - python=3.10
  - matplotlib
  - fitsio
  - numpy
  - pip
  - jax
  - schwimmbad
  - pytest
  - flake8
  - sphinx
  - myst-nb
  - sphinx-copybutton
  - sphinx-book-theme
  -pip:
    - fpfs
